### ISSUE TITLE
Unicode decode error

### ISSUE THREAD

**Issue by pcaversaccio** [daita-technologies/daita-python-library#3]
When using the current version `0.0.5`, I get the following unicode decoding warning:

```sh
'charmap' codec can't decode byte 0x90 in position 38: character maps to <undefined>
```

My first guess is that when we use `open` somewhere in the code, the encoding is set wrong or neglected.

**Comment by BEdaita** [comment]
Hi Pascal, You can share the screen related to the bug because I can't understand the bug.

**Comment by pcaversaccio** [comment]
First I run:

![image](https://user-images.githubusercontent.com/25297591/183697006-834387f6-70f6-4299-949d-798bdacaac12.png)

Thereafter:

![image](https://user-images.githubusercontent.com/25297591/183697079-9e6cbe6f-1687-48d2-9a87-0a17f609050e.png)

**Comment by BEdaita** [comment]
Hmm, I guess the bug is related to OS, You are using windows or MacOs.

**Comment by pcaversaccio** [comment]
Windows 11 right now. Yes it's an OS-related bug probably. Can test later with Ubuntu.
