### ISSUE TITLE
Show progress bar for uploads

### ISSUE THREAD

**Issue by pcaversaccio** [daita-technologies/daita-python-library#4]
Currently, the user does not get any information about the current state of the upload. We should implement a progress bar as terminal output to keep the user up-to-date.

**Comment by BEdaita** [comment]
Currently, I just show the process bar upload for image mode but if the use choose zip mode, the progress bar will be show on web.

**Comment by pcaversaccio** [comment]
in any case, we should put a process bar in the terminal for any mode. The user who uses the terminal wants a response / information from the terminal.
